# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Publish Pull Request

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      # - name: Set API_DOMAIN
      #   run: echo "REACT_NATIVE_API_DOMAIN=yellow" >> $GITHUB_ENV
      #
      - name: Publish to branch release channel
        run: expo publish --release-channel=pr-${{ github.event.number }}
        env:
          REACT_NATIVE_API_DOMAIN: ${{ secrets.DEV_API_URL }}
